### ISSUE TITLE
Add XEM Integration

### ISSUE THREAD

**Issue by noggl** [noggl/AniPlanrr#1]
Try using [XEM](https://thexem.info/doc) to relate TVDB IDs and AniList IDs

**Comment by Rojikku** [comment]
I investigated this.
1. XEM is not a complete list of anime
2. It only has TVDB IDs and aniDB IDs
3. I can't find any documented way to get one by inputting the other, but would be helpful for relating seasons in series
4. You can use [AOD](https://github.com/manami-project/anime-offline-database) to turn MAL IDs into aniDB IDs. I've already written most of the code for this in #4 and commented it out. I will leave it there in case you want it later.

**Comment by noggl** [comment]
I'm going to call this closed for now, since [AniListToTVDB](https://github.com/noggl/AniListToTVDB) is providing this functionality. The [mapping.csv](https://raw.githubusercontent.com/noggl/AniListToTVDB/main/mappings.csv) file works well for AniPlanrr
