### ISSUE TITLE
{SONARR,RADARR}ANIMEPATH are unnecessarily mandatory variables

### ISSUE THREAD

**Issue by Rojikku** [noggl/AniPlanrr#10]
As noted, script crashes instantly if these are not defined. This is bad behavior, because:
1. Not everyone is running both
2. I'm working on the importer feature, which wouldn't require that variable for operation.

**Comment by noggl** [comment]
I'll fix this now, relying on NoneTypes as bools broke a few things

I'm not sure if it will be helpful for the importer but there's a pretty complete mapping of AniList to TVDB/TMDB values over in https://github.com/noggl/AniListToTVDB. Adding the Type to that file is on the list, as is cleaning up the logs of Aniplanrr in general. There's way too much text flying along.

**Comment by Rojikku** [comment]
> I'm not sure if it will be helpful for the importer but there's a pretty complete mapping of AniList to TVDB/TMDB values over in [noggl/AniListToTVDB](https://github.com/noggl/AniListToTVDB). Adding the Type to that file is on the list, as is cleaning up the logs of Aniplanrr in general. There's way too much text flying along.

Saw that earlier, already started utilizing it. It appears that may have broken auto_fill somehow, because I seem to see the logs successfully looking up the IDs on every test, but I haven't really succeeded in investigating it.
Trying to figure out if I can get python to display a passed variable in a webpage without utilizing flask...

**Comment by noggl** [comment]
The code after `if AUTO_FILL_MAPPING` probably wouldn't get touched because things are matching via the .csv and that takes priority, right? Are you seeing an error in functionality related to autofill? Filling when it shouldn't be or not filling when it should?

**Comment by Rojikku** [comment]
I believe I'm seeing it not be filling when it should. I kept seeing the search successful output. It should always save searches when `AUTO_FILL_MAPPING` so I shouldn't ever see that twice.

Also, turns out getting a variable to display on a webpage...Slightly harder than expected.
Might be more efficient to just have the server spit the variable into a file, and have the docker container host that file on its own, rather than trying to write code to display a webpage. I'll look into it more tomorrow.

**Comment by noggl** [comment]
I don't think that's an issue with the auto fill, it's a bug where mapped shows are still searched for even though the mapped data will be used. As long as you don't see "Adding mapping: xyz" in your output, I think I know what you're taking about and can replicate it.

I'll clean up that behaviour when I clean up the logging and script organization overall, since it doesn't seem to affect functionality.
