### ISSUE TITLE
Error: Sonarr response is not an array

### ISSUE THREAD

**Issue by truevoltage** [noggl/AniPlanrr#12]
Checking for existing mapping for Kaguya-sama wa Kokurasetai: First Kiss wa Owaranai
Kaguya-sama wa Kokurasetai: First Kiss wa Owaranai is mapped to Kaguya-sama wa Kokurasetai: First Kiss wa Owaranai season 1
Dumping searchResponse to searchResponse-dump.txt
Error: Sonarr response is not an array
Dumping failedSonarrResponse to failedSonarrResponse-dump.txt
Traceback (most recent call last):
  File "code/aniplanrr.py", line 85, in <module>
    main()
  File "code/aniplanrr.py", line 74, in main
    runSonarr(sonarr, aniList)
  File "code/aniplanrr.py", line 31, in runSonarr
    newShowList = indexSonarrList(sonarr, newShowList, mapping, sonarrList)
  File "/opt/aniplanrr/AniPlanrr/code/sonarr.py", line 209, in indexSonarrList
    result['season'] = map['season']
TypeError: 'bool' object does not support item assignment

**Comment by noggl** [comment]
I can fix this this weekend (or today if I have time), can you share the full log file as well as your config file? 

and your searchResponse-dump.txt and failedSonarrResponse-dump.txt as well?

**Comment by truevoltage** [comment]
Not related to this i'm sure but I did edit anilist.py to query COMPLETED instead of PLANNING

[config.txt](https://github.com/noggl/AniPlanrr/files/12186188/config.txt)
[failedSonarrResponse-dump.txt](https://github.com/noggl/AniPlanrr/files/12186189/failedSonarrResponse-dump.txt)
[searchResponse-dump.txt](https://github.com/noggl/AniPlanrr/files/12186190/searchResponse-dump.txt)
[log.txt](https://github.com/noggl/AniPlanrr/files/12186191/log.txt)

**Comment by noggl** [comment]
Ok, here's the issue.

The show in question is considered a show by AniList but a movie by the tvdb.com. That's causing the script to fail, so I'll need to handle that, and let the code proceed, but I'm not sure what to do about the tv/movie mismatch. I _might_ be able to filter based on length but that seems pretty heavy handed and I don't think I want to do that.

I'll definitely stop the script from crashing, though, so standby for that.

**Comment by noggl** [comment]
Actually it looks like it's just an error on AniList's end. Would you submit an edit request on that page? If you scroll down you should see an edit button and you can change the type to movie.

They'll ask for a source, and you can put "This is a movie per length and https://myanimelist.net/anime/52198"

Still going to fix that crash though

**Comment by noggl** [comment]
Just pushed a change that should fix the error, let me know if that works.

It won't actually add the show until AniList fixes that wrong typing (and then it'll show up in radarr, not sonarr)

**Comment by noggl** [comment]
@truevoltage, is this still an issue for you, or have my instructions resolved it?

**Comment by truevoltage** [comment]
All good now
