### ISSUE TITLE
Radarr and Sonarr Filepaths are Hardcoded

### ISSUE THREAD

**Issue by Rojikku** [noggl/AniPlanrr#6]
Bug: The Radarr and Sonarr Filepaths are hardcoded.
Solution: Query the API to get them if there's only one, or accept from a variable, or both.
In the same vein, all the other "Add" settings are hardcoded, and that's not always for the best.

I will probably not fix this because I'm planning to work around it with an Import List solution, so leaving a bug report for tracking purposes.

**Comment by noggl** [comment]
Should be fixed now
